name: Build KernelSU

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4
        with:
          repository: LineageOS/android_kernel_xiomi_sm8250
          ref: lineage-23.2
          submodules: recursive

      - name: Setup Toolchain
        run: |
          sudo apt-get update && sudo apt-get install -y git bc bison flex libssl-dev gcc-aarch64-linux-gnu

      - name: Inject KernelSU
        run: |
          curl -LSs "https://raw.githubusercontent.com/tiann/KernelSU/main/kernel/setup.sh" | bash -

      - name: Build Kernel
        run: |
          export ARCH=arm64
          export CROSS_COMPILE=aarch64-linux-gnu-
          make O=out ARCH=arm64 NAMA_DEFCONFIG_MU_defconfig
          make -j$(nproc) O=out ARCH=arm64

      - name: Upload Kernel Image
        uses: actions/upload-artifact@v4
        with:
          name: Kernel_KSU
          path: out/arch/arm64/boot/Image.gz

