name: Build Kernel Apollo - Ultimate Custom Control

on:
  workflow_dispatch:

env:
  KERNEL_SOURCE: https://github.com/Nbil260602/android_kernel_xiaomi_sm8250
  KERNEL_BRANCH: main
  KERNEL_DEFCONFIG: vendor/apollo_defconfig

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git bc bison build-essential libssl-dev libelf-dev flex

      # 1. FIX DATA TYPE ERROR (Metode Echo + Cat yang 100% Anti-Gagal)
      - name: Patch Kernel Headers
        run: |
          echo "#include <linux/compat.h>" > temp_filter.h
          cat include/linux/filter.h >> temp_filter.h
          mv temp_filter.h include/linux/filter.h

      # 2. HACK TOTAL SELINUX & SISTEM KEAMANAN KERNEL
      - name: Force Absolute Permissive & Disable Security
        run: |
          sed -i 's/bool selinux_enforcing = true;/bool selinux_enforcing = false;/g' security/selinux/hooks.c 2>/dev/null || true
          sed -i 's/int selinux_enforcing = 1;/int selinux_enforcing = 0;/g' security/selinux/hooks.c 2>/dev/null || true
          echo "CONFIG_SECURITY_SELINUX=y" >> arch/arm64/configs/${{ env.KERNEL_DEFCONFIG }}
          echo "CONFIG_SECURITY_SELINUX_BOOTPARAM=y" >> arch/arm64/configs/${{ env.KERNEL_DEFCONFIG }}
          echo "CONFIG_SECURITY_SELINUX_BOOTPARAM_VALUE=0" >> arch/arm64/configs/${{ env.KERNEL_DEFCONFIG }}
          echo 'CONFIG_CMDLINE="androidboot.selinux=permissive enforcing=0"' >> arch/arm64/configs/${{ env.KERNEL_DEFCONFIG }}
          echo "CONFIG_CMDLINE_FORCE=y" >> arch/arm64/configs/${{ env.KERNEL_DEFCONFIG }}

      # 3. SUNTIK KERNELSU VERSI TERBARU
      - name: Patch Latest KernelSU
        run: |
          curl -LSs "https://raw.githubusercontent.com/tiann/KernelSU/main/kernel/setup.sh" | bash -

      # 4. UNDUH ALAT COMPILER (Proton Clang)
      - name: Download Toolchain (Proton Clang)
        run: |
          git clone --depth=1 https://github.com/kdrag0n/proton-clang clang

      # 5. PROSES COMPILE KERNEL (Dengan Pengabaian Warning -Wno-error)
      - name: Build Kernel
        run: |
          export PATH="$GITHUB_WORKSPACE/clang/bin:$PATH"
          make ARCH=arm64 O=out CC=clang HOSTCC="gcc -B/usr/bin/" HOSTCXX="g++ -B/usr/bin/" CROSS_COMPILE=aarch64-linux-gnu- CROSS_COMPILE_ARM32=arm-linux-gnueabi- KCFLAGS="-Wno-error" ${{ env.KERNEL_DEFCONFIG }}
          make ARCH=arm64 O=out -j$(nproc) CC=clang HOSTCC="gcc -B/usr/bin/" HOSTCXX="g++ -B/usr/bin/" CROSS_COMPILE=aarch64-linux-gnu- CROSS_COMPILE_ARM32=arm-linux-gnueabi- KCFLAGS="-Wno-error"

      # 6. UNGGAH HASIL JADI
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Kernel-Apollo-Bebas-Pembatas
          path: out/arch/arm64/boot/Image.gz-dtb
